[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediberg = "65y5sBTQ8rfth35N1qmH57z1s6JrhNevGTFfiTV6kait"

[programs.devnet]
prediberg = "65y5sBTQ8rfth35N1qmH57z1s6JrhNevGTFfiTV6kait"

[programs.mainnet]
prediberg = "65y5sBTQ8rfth35N1qmH57z1s6JrhNevGTFfiTV6kait"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[workspace]
members = ["programs/*"]
